// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"best-saas-designs.mdx": () => import("../content/docs/best-saas-designs.mdx?collection=docs"), "copywriting.mdx": () => import("../content/docs/copywriting.mdx?collection=docs"), "execution-rhythm-for-solo-founders.mdx": () => import("../content/docs/execution-rhythm-for-solo-founders.mdx?collection=docs"), "great-companies-to-track-as-a-entrepreneur.mdx": () => import("../content/docs/great-companies-to-track-as-a-entrepreneur.mdx?collection=docs"), "great-onboarding-flows.mdx": () => import("../content/docs/great-onboarding-flows.mdx?collection=docs"), "how-to-make-world-class-sofware.mdx": () => import("../content/docs/how-to-make-world-class-sofware.mdx?collection=docs"), "public-launch.mdx": () => import("../content/docs/public-launch.mdx?collection=docs"), "sites-best-for.mdx": () => import("../content/docs/sites-best-for.mdx?collection=docs"), "small-hacks-to-increase-branding.mdx": () => import("../content/docs/small-hacks-to-increase-branding.mdx?collection=docs"), "top-resources-to-follow-for-solofounders.mdx": () => import("../content/docs/top-resources-to-follow-for-solofounders.mdx?collection=docs"), "product/ai-cofounder.mdx": () => import("../content/docs/product/ai-cofounder.mdx?collection=docs"), "product/build.mdx": () => import("../content/docs/product/build.mdx?collection=docs"), "product/dashboard.mdx": () => import("../content/docs/product/dashboard.mdx?collection=docs"), "product/growth.mdx": () => import("../content/docs/product/growth.mdx?collection=docs"), "product/links.mdx": () => import("../content/docs/product/links.mdx?collection=docs"), "product/mcp.mdx": () => import("../content/docs/product/mcp.mdx?collection=docs"), "product/notes.mdx": () => import("../content/docs/product/notes.mdx?collection=docs"), "product/versions.mdx": () => import("../content/docs/product/versions.mdx?collection=docs"), }),
};
export default browserCollections;