-- =============================================================================
-- Migration: Add Growth Feature Tables
-- Purpose: Support version-based manual target-driven growth tracking
-- =============================================================================

CREATE TYPE public.growth_activity_type AS ENUM (
  'SEO',
  'COLD_DM',
  'COLD_EMAIL',
  'PAID_ADS',
  'AB_TEST',
  'ANALYTICS',
  'USER_FEEDBACK',
  'PRICING_OPTIMIZATION',
  'CRO',
  'ACCELERATOR',
  'REDDIT',
  'EVENTS',
  'CUSTOM'
);

-- =============================================================================
-- GROWTH PLANS
-- =============================================================================

CREATE TABLE public.growth_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nanoid TEXT NOT NULL UNIQUE DEFAULT public.generate_nanoid(18),
  project_id BIGINT NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  version_id BIGINT NOT NULL UNIQUE REFERENCES public.versions(id) ON DELETE CASCADE,
  deadline TIMESTAMP WITH TIME ZONE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- =============================================================================
-- GROWTH ACTIVITIES
-- =============================================================================

CREATE TABLE public.growth_activities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nanoid TEXT NOT NULL UNIQUE DEFAULT public.generate_nanoid(18),
  growth_plan_id BIGINT NOT NULL REFERENCES public.growth_plans(id) ON DELETE CASCADE,
  type public.growth_activity_type NOT NULL,
  custom_name TEXT,
  target_value INTEGER NOT NULL,
  completed_value INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- =============================================================================
-- GROWTH LOGS
-- =============================================================================

CREATE TABLE public.growth_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nanoid TEXT NOT NULL UNIQUE DEFAULT public.generate_nanoid(18),
  growth_activity_id BIGINT NOT NULL REFERENCES public.growth_activities(id) ON DELETE CASCADE,
  quantity INTEGER NOT NULL,
  note TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- =============================================================================
-- INDEXES
-- =============================================================================
CREATE INDEX IF NOT EXISTS idx_growth_plans_nanoid ON public.growth_plans(nanoid);
CREATE INDEX IF NOT EXISTS idx_growth_plans_version ON public.growth_plans(version_id);
CREATE INDEX IF NOT EXISTS idx_growth_activities_nanoid ON public.growth_activities(nanoid);
CREATE INDEX IF NOT EXISTS idx_growth_activities_plan ON public.growth_activities(growth_plan_id);
CREATE INDEX IF NOT EXISTS idx_growth_logs_nanoid ON public.growth_logs(nanoid);
CREATE INDEX IF NOT EXISTS idx_growth_logs_activity ON public.growth_logs(growth_activity_id);

-- =============================================================================
-- RLS POLICIES
-- =============================================================================

ALTER TABLE public.growth_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.growth_activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.growth_logs ENABLE ROW LEVEL SECURITY;

-- Plans
CREATE POLICY "Users can manage their growth plans" ON public.growth_plans
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.projects p
      WHERE p.id = growth_plans.project_id AND p.user_id = auth.uid()
    )
  );

-- Activities
CREATE POLICY "Users can manage their growth activities" ON public.growth_activities
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.growth_plans gp
      JOIN public.projects p ON gp.project_id = p.id
      WHERE gp.id = growth_activities.growth_plan_id AND p.user_id = auth.uid()
    )
  );

-- Logs
CREATE POLICY "Users can manage their growth logs" ON public.growth_logs
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.growth_activities ga
      JOIN public.growth_plans gp ON ga.growth_plan_id = gp.id
      JOIN public.projects p ON gp.project_id = p.id
      WHERE ga.id = growth_logs.growth_activity_id AND p.user_id = auth.uid()
    )
  );
