/**
 * Database Types for SaaSfollo
 * TypeScript types matching the Supabase schema
 * All entities now include a `nanoid` field used as the public-facing identifier
 * in URLs and API lookups, replacing the numeric `id` in external usage.
 */

// =============================================================================
// Base Types
// =============================================================================

export type TaskStatus = 'now' | 'next' | 'later' | 'done';
export type TaskPriority = 'low' | 'medium' | 'high' | null;
export type TaskCategory = string | null;
export type VersionStatus = 'active' | 'inactive';
export type LinkType = 'figma' | 'github' | 'vercel' | 'notion' | 'linear' | 'slack' | 'discord' | 'generic';

// =============================================================================
// Table Types
// =============================================================================

export interface Project {
  id: number;
  nanoid: string;
  user_id: string;
  name: string;
  description: string | null;
  icon_url: string | null;
  active_version_id: number | null;
  is_pinned: boolean;
  is_archived: boolean;
  created_at: string;
  updated_at: string;
}

export interface Version {
  id: number;
  nanoid: string;
  project_id: number;
  position: number;
  name: string;
  description: string | null;
  status: VersionStatus;
  prd: string | null;
  goals: string | null;
  deadline: string | null;
  created_at: string;
  updated_at: string;
  is_active?: boolean;
}

export interface Task {
  id: number;
  nanoid: string;
  project_id: number;
  kanban_column_nanoid: string | null;
  position: number | null;
  version_id: number | null;
  title: string;
  description: string | null;
  status: TaskStatus;
  priority: TaskPriority;
  category: TaskCategory;
  due_date: string | null;
  assignee: string | null;
  assigned_to?: string | null;
  is_completed: boolean;
  created_at: string;
  updated_at: string;
}

export interface Link {
  id: number;
  nanoid: string;
  project_id: number;
  url: string;
  tag: string | null;
  detected_type: LinkType;
  icon: string | null;
  label: string | null;
  created_at: string;
}

export interface Note {
  id: number;
  nanoid: string;
  project_id: number;
  title: string;
  content: string | null;
  created_at: string;
  updated_at: string;
}

export interface Secret {
  id: number;
  nanoid: string;
  project_id: number;
  key: string;
  encrypted_value: string;
  created_at: string;
}

export interface UserSettings {
  id: number;
  nanoid: string;
  user_id: string;
  secrets_pin_hash: string | null;
  created_at: string;
  updated_at: string;
}

// =============================================================================
// Insert Types (for creating new records)
// nanoid is auto-generated by the database, no need to include in inserts
// =============================================================================

export interface ProjectInsert {
  name: string;
  description?: string | null;
  icon_url?: string | null;
  is_pinned?: boolean;
  is_archived?: boolean;
}

export interface VersionInsert {
  project_id: number;
  position?: number;
  name: string;
  description?: string | null;
  status?: VersionStatus;
  prd?: string | null;
  goals?: string | null;
  deadline?: string | null;
}

export interface TaskInsert {
  project_id: number;
  kanban_column_nanoid?: string | null;
  position?: number | null;
  version_id?: number | null;
  title: string;
  description?: string | null;
  status?: TaskStatus;
  priority?: TaskPriority;
  category?: TaskCategory;
  due_date?: string | null;
  assignee?: string | null;
  is_completed?: boolean;
}

export interface LinkInsert {
  project_id: number;
  url: string;
  tag?: string | null;
  detected_type?: LinkType;
  icon?: string | null;
  label?: string | null;
}

export interface NoteInsert {
  project_id: number;
  title: string;
  content?: string | null;
}

export interface SecretInsert {
  project_id: number;
  key: string;
  encrypted_value: string;
}

export interface UserSettingsInsert {
  secrets_pin_hash?: string | null;
}

// =============================================================================
// Update Types (for updating existing records)
// =============================================================================

export interface ProjectUpdate {
  name?: string;
  description?: string | null;
  icon_url?: string | null;
  active_version_id?: number | null;
  is_pinned?: boolean;
  is_archived?: boolean;
}

export interface VersionUpdate {
  position?: number;
  name?: string;
  description?: string | null;
  status?: VersionStatus;
  prd?: string | null;
  goals?: string | null;
  deadline?: string | null;
}

export interface TaskUpdate {
  kanban_column_nanoid?: string | null;
  position?: number | null;
  version_id?: number | null;
  title?: string;
  description?: string | null;
  status?: TaskStatus;
  priority?: TaskPriority;
  category?: TaskCategory;
  due_date?: string | null;
  assignee?: string | null;
  is_completed?: boolean;
}

export interface LinkUpdate {
  url?: string;
  tag?: string | null;
  detected_type?: LinkType;
  icon?: string | null;
  label?: string | null;
}

export interface NoteUpdate {
  title?: string;
  content?: string | null;
}

export interface SecretUpdate {
  key?: string;
  encrypted_value?: string;
}

export interface UserSettingsUpdate {
  secrets_pin_hash?: string | null;
}

// =============================================================================
// Extended Types (with relations)
// =============================================================================

export interface ProjectWithStats extends Project {
  version_count?: number;
  task_count?: number;
  completed_task_count?: number;
  progress_percentage?: number;
  progress_label?: string;
  collaborator_count?: number;
  collaborator_emails?: string[];
  active_version?: Version | null;
  active_version_name?: string | null;
  current_user_role?: CollaboratorRole | 'owner';
}

export interface VersionWithTasks extends Version {
  tasks?: Task[];
  task_count?: number;
}

export interface TaskWithVersion extends Task {
  version?: Version | null;
}

export interface KanbanColumn {
  id: number;
  nanoid: string;
  project_id: number;
  title: string;
  description: string | null;
  position: number;
  is_done_column: boolean;
  created_at: string;
  updated_at: string;
}

export interface KanbanColumnInsert {
  project_id: number;
  title: string;
  description?: string | null;
  position?: number;
  is_done_column?: boolean;
}

export interface KanbanColumnUpdate {
  title?: string;
  description?: string | null;
  position?: number;
  is_done_column?: boolean;
}

// =============================================================================
// Collaboration Types
// =============================================================================

export type CollaboratorRole = 'owner' | 'editor' | 'reader';

export interface ProjectCollaborator {
  id: number;
  nanoid: string;
  project_id: number;
  user_id: string;
  email: string;
  role: CollaboratorRole;
  invited_by: string | null;
  invited_at: string;
  accepted_at: string | null;
  created_at: string;
}

export interface ProjectCollaboratorInsert {
  project_id: number;
  email: string;
  role?: CollaboratorRole;
}

// =============================================================================
// Growth Feature Types
// =============================================================================

export type GrowthActivityType =
  | 'SEO'
  | 'COLD_DM'
  | 'COLD_EMAIL'
  | 'PAID_ADS'
  | 'AB_TEST'
  | 'ANALYTICS'
  | 'USER_FEEDBACK'
  | 'PRICING_OPTIMIZATION'
  | 'CRO'
  | 'ACCELERATOR'
  | 'REDDIT'
  | 'EVENTS'
  | 'CUSTOM';

export interface GrowthPlan {
  id: number;
  nanoid: string;
  project_id: number;
  version_id: number;
  deadline: string;
  created_at: string;
  updated_at: string;
}

export interface GrowthActivity {
  id: number;
  nanoid: string;
  growth_plan_id: number;
  type: GrowthActivityType;
  custom_name: string | null;
  target_value: number;
  completed_value: number;
  created_at: string;
}

export interface GrowthLog {
  id: number;
  nanoid: string;
  growth_activity_id: number;
  quantity: number;
  note: string | null;
  created_at: string;
}

export interface GrowthPlanInsert {
  project_id: number;
  version_id: number;
  deadline: string;
}

export interface GrowthActivityInsert {
  growth_plan_id: number;
  type: GrowthActivityType;
  custom_name?: string | null;
  target_value: number;
  completed_value?: number;
}

export interface GrowthLogInsert {
  growth_activity_id: number;
  quantity: number;
  note?: string | null;
}

export interface GrowthPlanUpdate {
  deadline?: string;
}

export interface GrowthActivityUpdate {
  type?: GrowthActivityType;
  custom_name?: string | null;
  target_value?: number;
  completed_value?: number;
}

export interface GrowthLogUpdate {
  quantity?: number;
  note?: string | null;
}
